### ISSUE TITLE
dashboad does not work with zabbix 3.4 api

### ISSUE THREAD

**Issue by blka** [dav3860/zabbix_dashboard#12]
data: {"title":"DASHBOARD IN ERROR : undefined method `keys' for #Array:0x00000003a17720","status":"disa-blink","id":"#dashboard#_text","updatedAt":1503411326}
cound you check?

**Comment by t9nks** [comment]
I have got the same issue and found the fixed.

If you read the Appendix 2. Changes from 3.2 to 3.4 here -https://www.zabbix.com/documentation/3.4/manual/api/changes_3.2_-_3.4.

It mentions that ZBXNEXT-2102 dropped support of non-boolean values for flags **preservekeys**, startSearch, excludeSearch and countOutput. 

Just changed the below in zabbix.rb.

From
grps = serv.run {Zabby::Hostgroup.get("filter" =>{"name" => groups},"preservekeys" => **0**)}

to
grps = serv.run {Zabby::Hostgroup.get("filter" =>{"name" => groups},"preservekeys" => **true**)}

**Comment by blka** [comment]
thanks, it works now.
